### ISSUE TITLE
EPERM: operation not permitted, write in Electron

### ISSUE THREAD

**Issue by v-volaju** [jayralencar/sqlite-cipher.js#1]
Hi. I've been exploring with this library first with **nwjs** and now with **electron**. I got it working on nwjs but with electron(atom) it got an error (Error: EPERM: operation not permitted, write) when I tried to just load/require it in the app. I am using it with the[ minimal Electron app](https://github.com/atom/electron-quick-start.git) by loading it in index.html like so:

 `<html><head><title>H</title>
	<script type="text/javascript">
	try{
		var sqlite = require('sqlite-cipher');
		sqlite.connect(sample.db,'MyPassword'); 
			console.log(sqlite.run("SELECT * from country;"));
		}
	catch(err){
			console.log("Error::." + err);
		}
</script></head><body></body></html>`

I hope you can help me out. Thanks

**Comment by jayralencar** [comment]
Hi. I have not tested with electron. I will do. Please wait

**Comment by jayralencar** [comment]
@v-volaju see it [https://github.com/atom/electron/issues/2033](https://github.com/atom/electron/issues/2033)

**Comment by v-volaju** [comment]
Thanks for the reply. I have read that issue but can't quite figure out where to place that fix/workaround suggested on that thread. Anyway have made it work with electron yet?

**Comment by jayralencar** [comment]
Hi @v-volaju, I tested in electron. Look [https://github.com/jayralencar/electron-quick-start](https://github.com/jayralencar/electron-quick-start)

**Comment by jayralencar** [comment]
But, you have the problem when package, ok?
I'm looking it. Wait.

**Comment by jayralencar** [comment]
Solved in version 0.2.1
And commit [b0b2f6d](https://github.com/jayralencar/sqlite-cipher.js/commit/b0b2f6d6e10e0d054f301c94b5323d527fd86bca)

**Comment by v-volaju** [comment]
Thanks man. Took me a while to come back here.
