### ISSUE TITLE
sqlite-cipher and sqlite-sync crashes on NW.js 0.12.3

### ISSUE THREAD

**Issue by asanchezgomez** [jayralencar/sqlite-cipher.js#3]
Hi Jayr!

I am currently testing your sqlite-cipher package with NW.js, but when I try to create a table, **sqlite.run("CREATE TABLE COMPANYS(ID  INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL);");**, NW.js crash. It happens the same with sqlite-sync. Have you tried these packages in NW.js? It is necessary to install other applications before using sqlite-cipher?

Best regards, and thanks for your effort!

**Comment by jayralencar** [comment]
Hi Alejandro, I always use NW.js. And I never had any problems.
[Look it](http://clubedosgeeks.com.br/programacao/javascript/aplicativo-desktop-com-nwjs-angularjs-bootstrap-sqlite)
And
[https://github.com/ClubeDosGeeksCoding/nwjs-angularjs-sqlite](https://github.com/ClubeDosGeeksCoding/nwjs-angularjs-sqlite)

If you are generating the .exe, try to save the database file to a folder in %LOCALLAPPDATA%.

**Comment by asanchezgomez** [comment]
Hi Jayr!

First of all, I am not generating the .exe yet. I am running my app with nw.exe. I am trying to work with the following simple example:
https://github.com/asanchezgomez/error_database_nw 
If I try with **"> node main.js"** in the console, this code will work. But when I try with the NW.js (**>\path\to\nwjs\nw.exe \path\to\myapp**), it crashes when you click in "Database" link. I am running this app in a new **Windows7 64 bits virtual machine**, in which I only have installed **Node.js v4.4.0** and **NW.js v0.12.3**. I also have installed **Python 2.7.3** and **“npm install -g node-gyp”**, but the problem persists.

Thanks for your effort! I am looking forward to use your package in my app!:)

**Comment by jayralencar** [comment]
Hi,
I tested your app in a machine with Win 8.1, and node 4.2.2, and NW.js v0.12.3.** It's works**.

**You can send me the error?**

You could run my application? [https://github.com/ClubeDosGeeksCoding/nwjs-angularjs-sqlite](https://github.com/ClubeDosGeeksCoding/nwjs-angularjs-sqlite)

**Comment by asanchezgomez** [comment]
I think that the problem could be related with my new virtual machine, because it would not have all the first updates required for Windows7. So tonight I am going to find and install all available updates and tomorrow I will let you know if it works or not!

Thanks!

**Comment by jayralencar** [comment]
OK, tomorrow I'll test your app in Windows7.

**Comment by asanchezgomez** [comment]
Finally, sqlite-cipher works fine in my NW.js. The main problem was that my virtual machine with Windows 7 was new, so it did not have all required updates. So thank you for your help, and congratulations for your incredible work, because I think that there are not more packages in node for encrypting databases without OpenSSL!!

**Comment by jayralencar** [comment]
@asanchezgomez It was updated to 0.3.0

**Comment by asanchezgomez** [comment]
Thank you for let me know about your new version! Congratulations for your incredible work, I will try it as soon as possible :)

**Comment by asanchezgomez** [comment]
Hi @jayralencar ! I was working with your package and I would like to ask you two questions:

**1. What is the correct syntax for multiple primary keys and for foreign keys?**
I try with the following:
```
sqlite.run("CREATE TABLE table1 (appID text PRIMARY KEY, userPassword text);");
sqlite.run("CREATE TABLE table2 (appID text, filePath text, FOREIGN KEY (appID) REFERENCES table1(appID), PRIMARY KEY(appID, filePath));");
```
I think that the multiple primary key works fine, but the foreign key is not working because I'm doing some tests and it allowed me to insert as appID in table2 whatever I want.

**2. With the new format of the connect function, where do I have to pass the initialization vector if I use "aes-256-cbc" mode? Can I pass it as third parameter of the following function?**
` sqlite.connect('test/Database.enc','myPass','iv','aes-256-cbc');`

Thanks in advance!

**Comment by jayralencar** [comment]
#### 1
In sqlite-cipher and sqlite-sync you can use [pragma statements](https://www.sqlite.org/pragma.html). Run it:
```js
sqlite.run('PRAGMA foreign_keys = ON');
```
To enable foreign keys.  Once is enough.

#### 2 
Why you are using initialization vector?
This function accepts only three parameters: databaseFile, [password], [algorithm]

**Comment by jayralencar** [comment]
I think is best use INTEGER in Primary Keys, and AUTOINCREMENT.

**Comment by asanchezgomez** [comment]
Hi!

I've tried to use `sqlite.run('PRAGMA foreign_keys = ON');` in different possitions in my database code but it doesn't work. Could you show me an example in which you create two tables (one of these with a foreign key), and then insert a row with an invalid foreign key? I would like that the following code throws an exception:
```
sqlite.connect("database.db","myPass");
sqlite.run('PRAGMA foreign_keys = ON');
sqlite.run("CREATE TABLE table1 (appID integer PRIMARY KEY, userPassword text);");
sqlite.run("CREATE TABLE table2 (appID integer, filePath text, FOREIGN KEY (appID) REFERENCES table1(appID), PRIMARY KEY(appID, filePath));");
sqlite.insert('table2',{appID: 123, filePath: 'sample'});	
```
May be I'm making a stupid mistake, but I can see it...

On the other hand, in CBC mode is required an IV in order to produce different cipher texts without modifying the encryption key. I think if the IV is not provided, you are using 0 IV. The disadvantage of a null IV (or a deterministic IV) is that it is vulnerable to dictionary attacks. [Reference](http://stackoverflow.com/questions/20888851/does-aes-cbc-really-requires-iv-parameter)

Thanks for your advices!

**Comment by asanchezgomez** [comment]
In addition, I've found that the following query is not working in 0.3.0 version when it works in 0.2.0 version:
var rows = sqlite.run("SELECT * from table WHERE attr1 = '?' and attr2 = '?'",[attr1],[attr2]);

The error which appears in the terminal is:

**Comment by jayralencar** [comment]
Hi @asanchezgomez ,
1 - I tried it:
```js
var sqlite = require("sqlite-cipher");

sqlite.connect("database.db","myPass");
sqlite.run('PRAGMA foreign_keys = OFF');
sqlite.run("CREATE TABLE table1 (appID integer PRIMARY KEY, userPassword text);");
sqlite.run("CREATE TABLE table2 (appID integer, filePath text, FOREIGN KEY (appID) REFERENCES table1(appID), PRIMARY KEY(appID, filePath));");
sqlite.insert('table2',{appID: 123, filePath: 'sample'});   
```
And works. Look:
```
Error: UNIQUE constraint failed: table2.appID, table2.filePath
```

2 - Ok, I'll update to provide IV. Wait. Thanks for contributing.

3 - The way to do it is:
```js
var rows = sqlite.run("SELECT * from table WHERE attr1 = ? and attr2 = ?",[attr1, attr2]);
```
Use <strong>?</strong> without quotes.

**Comment by asanchezgomez** [comment]
1. It is with `PRAGMA foreign_keys = OFF` or `PRAGMA foreign_keys = ON`?. I think it has to be with the second option. However, it works fine for me in NW.js project that I have on Windows with node 4.4.0. On the other hand, with the same project on Linux with node 0.12.2 it does not work. So I'm going to update this last node and I let you know.

2. Ok thank you for your efforts!! I'll be waiting for the new version :)

3. As soon as I can fixed my problem with the foreign keys, I will try without quotes!

Best regards.

**Comment by jayralencar** [comment]
Ok man, I will close this issue. Open another if you need. Ok?

**Comment by asanchezgomez** [comment]
Okey!
