### ISSUE TITLE
Update password of database previously encrypted

### ISSUE THREAD

**Issue by asanchezgomez** [jayralencar/sqlite-cipher.js#6]
Hi @jayralencar !

I would like to ask you about the best way of updating the password of database encrypted. It would be a good idea to have a specific method to perform this action. I think that the only alternative is to decrypt and encrypt again the database with the new password:

```
var sqlite = require('sqlite-cipher');

sqlite.connect('myEncrypedFile.db','MyPassword');
sqlite.run("CREATE TABLE COMPANYS(ID  INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL);");
sqlite.insert("COMPANYS",{NAME:"My COMPANY"});

sqlite.decrypt('myEncrypedFile.db', 'myDecrypedFile.db','MyPassword');
sqlite.encrypt('myDecrypedFile.db','myEncrypedFile.db' ,'MyPassword2');
sqlite.connect('myEncrypedFile.db','MyPassword2');
sqlite.insert("COMPANYS",{NAME:"My COMPANY2"});
sqlite.decrypt('myEncrypedFile.db', 'myDecrypedFile.db','MyPassword2');

sqlite.close();
```
The problem of this approach is you have to temporarily decrypt the database, which is not a good idea...

Thanks!

**Comment by jayralencar** [comment]
I'll work on that.

**Comment by asanchezgomez** [comment]
okey thanks @jayralencar !

**Comment by jayralencar** [comment]
Hello @asanchezgomez fixed in [0.3.4](https://github.com/jayralencar/sqlite-cipher.js/releases/tag/v0.3.4).

**Comment by asanchezgomez** [comment]
Okey thank you for all your efforts @jayralencar ! I will test all new features this weekend!

**Comment by asanchezgomez** [comment]
Hi @jayralencar ! I've test it on node 4.4.0 on Windows and it works fine. I will try it on Ubuntu during this weekend and I will let you know in order to close this issue. On the other hand, I think that it is also really necessary to add the functionality of Initialization Vector modification.

**Comment by jayralencar** [comment]
Ok, I'll provide.
