### ISSUE TITLE
Check encrypted database password

### ISSUE THREAD

**Issue by asanchezgomez** [jayralencar/sqlite-cipher.js#7]
Hi again @jayralencar !

It is possible to check if a specific password is the correct for a encrypted database?

I thought  that if you try to connect to a database with a wrong password, your package will throw a Sqlite error, but it does not happen. I'm playing with the next little example:

```
var sqlite = require('sqlite-cipher');

sqlite.connect('myEncrypedFile.db','MyPassword');
sqlite.connect('myEncrypedFile.db','MyPassword2');
console.log("without SQLITE error");

sqlite.run("CREATE TABLE COMPANYS(ID  INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL);");
console.log("without SQLITE error");

sqlite.insert("COMPANYS",{NAME:"My COMPANY"});
console.log("SQLITE error: file is encrypted or is not a database");
```
I don't know if you could make a method for testing a password or if you could recommend me a way to do it with the current version.

Thanks for your effort!

**Comment by jayralencar** [comment]
Hi @asanchezgomez,
I fixed it in [0.3.2](https://github.com/jayralencar/sqlite-cipher.js/releases/tag/v0.3.2). Please install it, and try:
```js
try{
	sqlite.connect('myEncrypedFile.db','MyPassword2');
}catch(x){
	console.log(x)
}
```
If you dont use try/catch it will display a error.

**Comment by asanchezgomez** [comment]
Okey thanks @jayralencar ! I will try it during this week and I let you know the results! :)

**Comment by asanchezgomez** [comment]
Could you confirm me that this example throws an exception?

```
var sqlite = require('sqlite-cipher');

try{
    sqlite.connect('myEncrypedFile.db','MyPassword');
		console.log("OK 1");
}catch(x){
		console.log("ERROR 1");
    console.log(x)
}
try{
    sqlite.connect('myEncrypedFile.db','MyPassword2');
		console.log("OK 2");
}catch(x){
		console.log("ERROR 2");
    console.log(x)
}
console.log("Point 1");

sqlite.run("CREATE TABLE COMPANYS(ID  INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT NOT NULL);");
console.log("Point 2");

sqlite.insert("COMPANYS",{NAME:"My COMPANY"});
console.log("Point 3");
```
I'm trying to catch the "ERROR 2" but my output is:

```
OK 1
OK 2
Point 1
Point 2
Point 3
```

Thanks!

**Comment by jayralencar** [comment]
```js
var sqlite = require('sqlite-cipher');
try{
	sqlite.connect('Database.rec','myPass','aes-256-ctr');
}catch(x){
	console.log(x)
}
```
Run this code with node.
Change to:
```js
var sqlite = require('sqlite-cipher');
try{
	sqlite.connect('Database.rec','myPass2','aes-256-ctr');
}catch(x){
	console.log(x)
}
```
Run again.

**Comment by asanchezgomez** [comment]
I've followed these two steps and it does not throw any exception. I work with node v5.10.0.

**Comment by jayralencar** [comment]
Install [0.3.3](https://github.com/jayralencar/sqlite-cipher.js/releases/tag/v0.3.3) and try again.

**Comment by asanchezgomez** [comment]
I don't know if my project will work in a previous node version but I will test it during this weekend. Do you know why it does not work in the last node version? I think that we have to get it to work in the last stable node version :)

**Comment by jayralencar** [comment]
What version are you using?

**Comment by asanchezgomez** [comment]
node v5.10.0

**Comment by jayralencar** [comment]
These days I have tested in v4.3.1. And sqlite-cipher works. 

I think you'll like this: [http://baseljs.github.io/](http://baseljs.github.io/)

**Comment by asanchezgomez** [comment]
Okey, I will try with v4.3.1 at weekend. On the other hand, congratulations for your Basel project!! I think that it could be a good option for my next project!! :)

**Comment by asanchezgomez** [comment]
Hi @jayralencar ! I've test it on node 4.4.0 on Windows and it works fine. I will try it on Ubuntu during this weekend and I will let you know in order to close this issue.
